### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by robmarkcole** [Fuermohao/EMP-IDE#8]
HI
I have started a project here https://github.com/robmarkcole/circuitpython-on-home-assistant
Next I want to create a web UI for using the boards, viewable in the browser, and Deployable via Docker. I would then roll it out as a home-assistant addon at https://github.com/hassio-addons
Probably you have the experience to do this quite easily, perhaps using Flask? 
Let me know if this is of interest, we have many home-assistant users :-)
Cheers

**Comment by Fuermohao** [comment]
As for your Project:
I do have interest. But I think I should spend a little time to learn it.
CircuitPython seems to only support 8266 and several adafriut's own development boards?
I prefer micropython more.

**Comment by robmarkcole** [comment]
OK so you are connecting via the webREPL.. Yes will require serial connection for circuitpython, as it doesn't have webREPL. As you say, CircuitPython supports 8266 and their own range of boards, which I appreciate will be of more limited interest, but very beginner friendly. 
I will keep an eye on the development here, let me know if you need any beta testers for CircuitPython integration etc.
Thanks

**Comment by Fuermohao** [comment]
>  but very beginner friendly.

I prefer your point as well as MicroPython. That's why I started the project 'Easy MicroPython(EMP)'.
and our purpose is just to `make things easy`
Maybe we can find a balance between CircuitPython and Micropython. 

> I will keep an eye on the development here, 

Thanks for your attention. 

> let me know if you need any beta testers for CircuitPython integration etc.

No Problem!
